### ISSUE TITLE
gulp build fails with docpress/gh-pages

### ISSUE THREAD

**Issue by ghost** [Kikobeats/uno-urban#3]
When I execute `gulp build` I get the following error:

```
[21:28:31] Starting 'gh-pages'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn docpress ENOENT
  at exports._errnoException (util.js:870:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
  at Function.Module.runMain (module.js:443:11)
  at startup (node.js:139:18)
  at node.js:968:3
```

Any idea how I can resolve this?

**Comment by Kikobeats** [comment]
Hmm I supose that you don't have docpress installed as global package (npm install -g docpress)

On the other hand, do not worry about this, I mean docs are auto generated and released in each uno-urban version, so actually you don't need to generate it.
