### ISSUE TITLE
How to change home page button colors?

### ISSUE THREAD

**Issue by jdchandler** [Kikobeats/uno-urban#30]
I read the guide and edited the _variables.scss file

I found that I had to rebuild

When I use gulp I get the following:

[06:34:51] Failed to load external module coffee-script/register
[06:34:51] Failed to load external module coffee-script
/data/justinchandler-blog2/themes/uno-urban-4.0.1/gulpfile.coffee:3
# -- Dependencies --------------------------------------------------------------
^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)

I can't seem get it to take my new settings or rebuild

**Comment by Kikobeats** [comment]
what's node version are you using? Try with the last stable or LTS

**Comment by jdchandler** [comment]
root@Shad0wFlix:/data/justinchandler-blog2/themes/uno-urban-4.0.1# npm version
{ 'uno-urban': '4.0.1',
  npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '55.1',
  modules: '46',
  node: '4.2.6',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }

root@Shad0wFlix:/data/justinchandler-blog2/themes/uno-urban-4.0.1# gulp
[15:19:44] Failed to load external module coffee-script/register
[15:19:44] Failed to load external module coffee-script
/data/justinchandler-blog2/themes/uno-urban-4.0.1/gulpfile.coffee:3
# -- Dependencies --------------------------------------------------------------
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by Kikobeats** [comment]
node v4 is too old, try run it with node 8 or higher
